accounts:
  - username: xxxxxxxxxx
    password: **********
    orders:
      - trainDate:
          - 2018-03-07
          - 2018-03-08
          - 2018-03-09
        backTrainDate: 2018-03-07
        fromStationName: 徐州
        toStationName: 上海
        trains:
          - G225
          - G1969
        planPepoles:
          - 李四
        seatTypes:
          - 二等座
          - 一等座
  - username: yyyyyyyyyy
    password: **********
    orders:
      - trainDate:
          - 2018-03-07
          - 2018-03-08
          - 2018-03-09
        backTrainDate: 2018-03-07
        fromStationName: 北京
        toStationName: 上海
        trains:
          - G1969
        planPepoles:
          - 张三
        seatTypes:
          - 一等座
          - 特等座
